"""Configuration validation and init command for xpyd-acc.

Provides:
- generate_starter_config(): produces a well-commented TOML starter file
- validate_config(): checks a TOML file for unknown keys and type mismatches
"""

from __future__ import annotations

import sys

if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomllib
    except ModuleNotFoundError:
        import tomli as tomllib  # type: ignore[no-redef]

from dataclasses import fields
from pathlib import Path
from typing import Any

from xpyd_acc.config import (
    BatchConfig,
    DefaultsConfig,
    KVConfig,
    MatchingConfig,
    ReportConfig,
)

# Map of known TOML sections to their dataclass types
_SECTION_MAP: dict[str, type] = {
    "defaults": DefaultsConfig,
    "batch": BatchConfig,
    "kv": KVConfig,
    "report": ReportConfig,
    "matching": MatchingConfig,
    "profiles": dict,  # special: profiles are free-form
}

# Python type to TOML type name for error messages
_TYPE_NAMES: dict[type, str] = {
    str: "string",
    int: "integer",
    float: "number",
    bool: "boolean",
}


STARTER_CONFIG = """\
# xpyd-acc configuration file
# Generated by: xpyd-acc init
# Docs: https://github.com/xPyD-hub/xPyD-acc

[defaults]
# baseline = "http://localhost:8000/v1"
# target = "http://localhost:8001/v1"
# model = "default"
# api_key = "no-key"
# max_tokens = 64
# retries = 3
# retry_delay = 1.0
# temperature = 0.0
# top_p = 1.0
# seed = 42
# timeout = 120.0
# rate_limit = 10.0

[batch]
# concurrency = 5
# logprob_gap_threshold = 0.1
# dataset = "gsm8k"
# fail_threshold = 0.05
# deduplicate = false
# cache_dir = ".xpyd-acc-cache"
# cache_ttl = 3600.0

[kv]
# max_abs_threshold = 0.001
# cosine_threshold = 0.999

[report]
# output = "report.html"

[matching]
# normalize_whitespace = false
# ignore_case = false
# numeric_tolerance = 0.001

# [profiles.greedy]
# temperature = 0.0
# seed = 42

# [profiles.stochastic]
# temperature = 0.7
"""


def generate_starter_config(output: Path, *, force: bool = False) -> str:
    """Write a starter xpyd-acc.toml config file.

    Args:
        output: Path to write the config file.
        force: If True, overwrite existing file.

    Returns:
        The path written to as a string.

    Raises:
        FileExistsError: If the file exists and force is False.
    """
    if output.exists() and not force:
        raise FileExistsError(f"Config file already exists: {output} (use --force to overwrite)")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(STARTER_CONFIG, encoding="utf-8")
    return str(output)


def validate_config(path: Path) -> list[str]:
    """Validate a TOML config file for unknown keys and type mismatches.

    Args:
        path: Path to the TOML config file.

    Returns:
        List of error/warning messages. Empty list means valid.

    Raises:
        FileNotFoundError: If the config file does not exist.
    """
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")

    with path.open("rb") as f:
        try:
            raw = tomllib.load(f)
        except Exception as exc:
            return [f"TOML parse error: {exc}"]

    issues: list[str] = []

    for section_name, section_data in raw.items():
        if section_name not in _SECTION_MAP:
            issues.append(f"warning: unknown section [{section_name}]")
            continue

        if not isinstance(section_data, dict):
            issues.append(
                f"error: [{section_name}] must be a table, "
                f"got {type(section_data).__name__}"
            )
            continue

        cls = _SECTION_MAP[section_name]

        # profiles are free-form
        if cls is dict:
            continue

        valid_fields = {f.name: f for f in fields(cls)}
        for key, value in section_data.items():
            if key not in valid_fields:
                issues.append(f"warning: [{section_name}] unknown key '{key}'")
                continue

            f = valid_fields[key]
            expected = _extract_base_type(f.type)
            if expected and not isinstance(value, expected):
                # Allow int where float is expected
                if expected is float and isinstance(value, int):
                    continue
                exp_name = _TYPE_NAMES.get(expected, expected.__name__)
                issues.append(
                    f"error: [{section_name}].{key} expected {exp_name}, "
                    f"got {type(value).__name__}"
                )

    return issues


def _extract_base_type(type_hint: Any) -> type | None:
    """Extract the base type from a type hint string or type for validation.

    Handles: str, int, float, bool, 'str | None', etc.
    Returns None for complex types we can't easily validate.
    """
    if isinstance(type_hint, type):
        return type_hint

    if isinstance(type_hint, str):
        # Handle 'str | None', 'float | None', etc.
        clean = type_hint.replace(" ", "").replace("None", "").replace("|", "").strip()
        type_map = {"str": str, "int": int, "float": float, "bool": bool}
        return type_map.get(clean)

    return None
